language: r

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/covr

cache: packages

warnings_are_errors: false

after_script:
  - Rscript -e 'lintr::lint_package()'

after_success:
  - Rscript -e 'covr::codecov()'
